### ISSUE TITLE
代理伺服器设定疑问

### ISSUE THREAD

**Issue by githubberrys** [norlover/pubg-radar-traffic-token#1]
老铁您好:

使用mitmproxy，并开启https代理设定在本机127.0.0.1:8080
并且设定Windows 的代理伺服器为127.0.0.1:8080
所有流量都会通过代理伺服器, 但唯独pubg没有通过代理伺服器,
请问老铁是如何设定, 让pubg能够走代理伺服器呢

**Comment by norlover** [comment]
6个月以前了，我现在已经不玩了，可能已经变化了
